os:
    - linux
    - osx

script:
    - cd test
    - test "$(../Perun echo_foo)" == "foo"
    - test "$(../Perun echo_foo bar)" == "foo"
    - test "$(../Perun echo_bar_and_args)" == "bar"
    - test "$(../Perun echo_bar_and_args arg)" == "bar arg"
    - test "$(../Perun echo_bar_and_args arg1 arg2)" == "bar arg1 arg2"
    - test "$(../Perun echo_empty_or_first_arg)" == "empty"
    - test "$(../Perun echo_empty_or_first_arg foo)" == "foo"
