#!/bin/bash

function fail() {
    local msg exit_code
    msg=$1
    exit_code=$2
    echo "$msg"
    exit "$exit_code"
}

if [[ ! -e Perunfile ]]; then
    echo "No Perunfile found, create one? (Y/n): "
    read -r create
    if [[ $create == "Y" ]]; then
        {
            echo '#!/bin/bash'
            echo '# For use with Perun (https://github.com/boris-spas/perun)'
        } > Perunfile
    else
        fail "No Perunfile" 1
    fi
fi

if [[ $# -eq 0 ]]; then
    fail "Task?" 2
fi

function _s() {
    local name=$1
    shift
    {
        echo ""
        echo "function $name() {"
        echo "    $*"
        echo "}"
    } >> "$PERUNFILE"
    tail -n 3 "$PERUNFILE"
}

PERUNFILE="$(pwd)"/Perunfile
# shellcheck source=/dev/null
source "$PERUNFILE"
TASK=$1
shift
$TASK "$@"
